[tool.poetry]
name = "child"
version = "0.1.0"
description = ""
license = "MIT"
authors = []

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
child-cli = 'child:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
